name = "loft"
compatibility_date = "2025-09-15"
send_metrics = false
main = "build/worker/shim.mjs"

[assets]
directory = "./dist/public"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = ["/api/*"]

[build]
command = "(./build.sh --features api) && cargo install -q worker-build && worker-build --release"
watch_dir = ["./src"]

# [observability.logs]
# enabled = true
